#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Oct 31 14:51:16 CDT 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim ram_testbench_behav -key {Behavioral:sim_1:Functional:ram_testbench} -tclbatch ram_testbench.tcl -log simulate.log"
xsim ram_testbench_behav -key {Behavioral:sim_1:Functional:ram_testbench} -tclbatch ram_testbench.tcl -log simulate.log

